# YOLOv8 Configuration for Sperm Detection
# Dataset configuration
path: '../data/datasets/sperm_dataset'  # dataset root dir
train: 'images/train'  # train images (relative to 'path')
val: 'images/val'      # val images (relative to 'path')
test: 'images/test'    # test images (optional)

# Classes
nc: 1  # number of classes
names: ['sperm']  # class names

# Model configuration
model: 'yolov8n.pt'  # base model (nano version for speed)
epochs: 100
batch: 16
imgsz: 640
lr0: 0.01
weight_decay: 0.0005
momentum: 0.937
warmup_epochs: 3
warmup_momentum: 0.8
warmup_bias_lr: 0.1

# Augmentation
hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7    # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4    # image HSV-Value augmentation (fraction)
degrees: 0.0  # image rotation (+/- deg)
translate: 0.1 # image translation (+/- fraction)
scale: 0.5    # image scale (+/- gain)
shear: 0.0    # image shear (+/- deg)
perspective: 0.0 # image perspective (+/- fraction), range 0-0.001
flipud: 0.0   # image flip up-down (probability)
fliplr: 0.5   # image flip left-right (probability)
mosaic: 1.0   # image mosaic (probability)
mixup: 0.0    # image mixup (probability)

# Training parameters
patience: 50  # epochs to wait for no improvement
save_period: -1 # Save checkpoint every x epochs (disabled if < 1)
save: true
exist_ok: false
pretrained: true
optimizer: 'SGD'  # optimizer (SGD, Adam, AdamW, RMSProp)
verbose: true
seed: 0
deterministic: true
single_cls: true  # train as single-class dataset
rect: false  # rectangular training
cos_lr: false
close_mosaic: 10
amp: true  # Automatic Mixed Precision training

# Validation parameters
val: true
split: val
save_json: false
save_hybrid: false
conf: 0.001
iou: 0.6
max_det: 300
half: false
dnn: false
plots: true

# Prediction parameters
source: null
show: false
save_txt: false
save_conf: false
save_crop: false
hide_labels: false
hide_conf: false
vid_stride: 1
line_thickness: 3
visualize: false
augment: false
agnostic_nms: false
classes: null
retina_masks: false
boxes: true

# Export parameters
format: torchscript
keras: false
optimize: false
int8: false
dynamic: false
simplify: false
opset: null
workspace: 4
nms: false

# Hyperparameters
box: 7.5          # box loss gain
cls: 0.5          # cls loss gain
dfl: 1.5          # dfl loss gain